### ISSUE TITLE
Code a template for all the pages the app will need

### ISSUE THREAD

**Issue by alexanderjhughes** [Right-Pay/Software_Development_CS389#14]

**Comment by Tibesnoff** [comment]
See the main screen Template. This includes the navbar and the top bar. Everything can be static for right now. Add a possibility to link to other screens

**Comment by alexanderjhughes** [comment]
- For #23

**Comment by Tibesnoff** [comment]
Editing to create a batch or python script to auto setup a new page

**Comment by alexanderjhughes** [comment]
This needs to be a template for screens. So it should follow along with the LocationSettings and ProfileSettings files.
Use this package:
https://medium.com/@robertsavian/generate-template-files-with-ease-19b320615359
