### ISSUE TITLE
Hook up forgot username and password logic

### ISSUE THREAD

**Issue by Tibesnoff** [Right-Pay/Software_Development_CS389#35]
**Description**
Currently forgot username and password logic is not set up

**Acceptance Criteria**

- When navigating to forgot password or username you are prompted to enter your email
- If your email exists you will get an email with a code
- That code will be used to fill in a box to verify and then you will be asked to change your password

**Additional context (optional)**

**Comment by alexanderjhughes** [comment]
Check if Auth0 does this? Is it part of the free tier?
