### ISSUE TITLE
Find user's location

### ISSUE THREAD

**Issue by Tibesnoff** [Right-Pay/Software_Development_CS389#7]
**Description**

The user's location should be found and displayed using an API such as google maps

**Acceptance Criteria**

User's location is found
User's location can be seen on the app

**Additional context (optional)**
https://developers.google.com/maps/apis-by-platform

**Comment by Tibesnoff** [comment]
Look into map box

**Comment by alexanderjhughes** [comment]
- For #18

**Comment by Tibesnoff** [comment]
https://blog.logrocket.com/react-native-geolocation-complete-tutorial/

Create a file that can call this and give data

Probably a const with the location object

Create a type in the type folder for a location object

Try to add to top nav bar in right corner just coordinates
