### ISSUE TITLE
Hook Up Credit Card Front End with Back End

### ISSUE THREAD

**Issue by Tibesnoff** [Right-Pay/Software_Development_CS389#70]
**Description**
Once the credit card from the end is finished, it needs to be hooked up to the backend

**Acceptance Criteria**

- Add and Delete are hooked up for credit cards
- Add and Delete are hooked up for rewards

**Additional context (optional)**

**Comment by alexanderjhughes** [comment]
Blocked by #50

**Comment by alexanderjhughes** [comment]
Worked with @Tibesnoff  to implement this
