### ISSUE TITLE
Card backend

### ISSUE THREAD

**Issue by Tibesnoff** [Right-Pay/Software_Development_CS389#8]
**Description**

The backend of the credit card rewards screen

**Acceptance Criteria**

Database tables will be created to hold the data for each credit card's rewards. Tables should include one for credit card data and one for rewards with ids related to the credit card table

**Additional context (optional)**

**Comment by Tibesnoff** [comment]
- For #18 
- For #52

**Comment by alexanderjhughes** [comment]
Have everything working as of November 9th except for linking rewards

**Comment by alexanderjhughes** [comment]
Way to broad, does not include rewards.
