### ISSUE TITLE
Login front-end

### ISSUE THREAD

**Issue by lecler17** [Right-Pay/Software_Development_CS389#9]
**Description**
A front-end page where the user enters their info to log in

**Acceptance Criteria**
Textbox for username
Textbox for password
Button to log in
Texts that indicate which box is which ("Username:", "Password:")
Forgot password
New user

**Additional context (optional)**

**Comment by Tibesnoff** [comment]
See the app flats welcome, login, and register page.

Welcome
- Log In and Sign up button can nav to their respective pages

Login

- Sign Up takes you to the register screen
- Create logic to test if the username and password are correct. This will need to reach out to the backend so use a fake endpoint for now that just goes true for testing
- Create logic to test if things are filled in
- Don't worry about adding a link for the forgot username and password section. Make it static for now
- Once you click the Log In page it takes you to the main screen which will land on the location page

**Comment by alexanderjhughes** [comment]
- For #23
